# Ket noi Database
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mysql

# Cau hinh JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Cau hinh Swagger UI (OpenAPI)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Ten ung dung (Da duoc tach dong)
spring.application.name=hotel_system